data_directories:
  raw_dir: "data/raw"
  processed_dir : "data/processed"
  features_dir: "data/features"
  signals_dir: "data/signals"

transcripts_data:
  dataset_repo: "kurry/sp500_earnings_transcripts"
  tickers: ["AAPL", "MSFT"]
  start_year: 2020
  end_year: 2025

transcripts_processing:
  max_seq_length: 512
  stride: 50

nlp_model:
  hf_model_id: "yiyanghkust/finbert-tone"
  batch_size: 16
